name: Check build
on:
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build artifact
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: './cajitasdeamor/package-lock.json'
    - name: Move to directory 1
      run: cd cajitasdeamor
    - name: Move to directory 2
      run: cd cajitasdeamor
    - name: Comprobar
      run: ls
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
